# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/batch/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/batch/
    - sdk/resourcemanager/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: batch
    ArtifactName: packages
    Artifacts:
    - name: Azure.ResourceManager.Batch
      safeName: AzureResourceManagerBatch
    - name: Azure.Data.Batch
      safeName: AzureDataBatch
